CREATE TABLE IF NOT EXISTS worker (
  "id" SERIAL PRIMARY KEY,
  "username" VARCHAR(128) UNIQUE NOT NULL,
  "password" VARCHAR(512) NOT NULL,
  "nickname" VARCHAR(128) NOT NULL,
  "phone_number" VARCHAR(32) NOT NULL,
  "email" VARCHAR(64) NOT NULL
);