version: '3'

services:
  back-eurekaserver:
    container_name: back-eurekaserver
    image: devtae/back-eurekaserver
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - eureka_network

  back-apigateway:
    container_name: back-apigateway
    image: devtae/back-apigateway
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
    depends_on:
      - back-eurekaserver
    networks:
      - eureka_network

  back-worker-database:
    container_name: back-worker-database
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BACK_WORKER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
    networks:
      - database_network

  back-worker:
    container_name: back-worker
    image: devtae/back-worker
    restart: on-failure
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://back-worker-database:5432/back_worker
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9412
    depends_on:
      - back-worker-database
      - back-eurekaserver
      - back-apigateway
    volumes:
      - ./logs:/logs
    networks:
      - eureka_network
      - database_network

  back-work-database:
    container_name: back-work-database
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BACK_WORK}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
    networks:
      - database_network

  back-work:
    container_name: back-work
    image: devtae/back-work
    restart: on-failure
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://back-work-database:5432/back_work
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9412
    depends_on:
      - back-work-database
      - back-eurekaserver
      - back-apigateway
    volumes:
      - ./logs:/logs
    networks:
      - eureka_network
      - database_network

#  back-dashboard:
#    container_name: back-dashboard
#    image: devtae/back-dashboard
#    restart: on-failure
#    ports:
#      - "9003:9003"
#    environment:
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
#      SPRING_ZIPKIN_BASE_URL: http://zipkin:9412
#    depends_on:
#      - back-eurekaserver
#      - back-apigateway
#    volumes:
#      - ./logs:/logs
#    networks:
#      - eureka_network
#      - database_network

#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
#    restart: on-failure
#    environment:
#      - discovery.type=single-node
#      - path.logs=
#        - /logs/back-worker-log4j2.log
#        - /logs/back-work-log4j2.log
#        - /logs/back-dashboard-log4j2.log
#    ports:
#      - "9200:9200"
#    volumes:
#      - ./logs:/logs
#    networks:
#      - eureka_network

#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.15.0
#    restart: on-failure
#    ports:
#      - "5601:5601"
#    networks:
#      - eureka_network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: on-failure
    ports:
      - "9411:9411"
    networks:
      - eureka_network

networks:
  database_network:
  eureka_network:
