version: '3'

services:
  back-eurekaserver:
    container_name: back-eurekaserver
    image: devtae/back-eurekaserver
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - eureka_network

  back-apigateway:
    container_name: back-apigateway
    image: devtae/back-apigateway
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
    depends_on:
      - back-eurekaserver
    networks:
      - eureka_network

  back-worker-database:
    container_name: back-worker-database
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BACK_WORKER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
    networks:
      - database_network

  back-worker:
    container_name: back-worker
    image: devtae/back-worker
    restart: on-failure
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://back-worker-database:5432/back_worker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
    depends_on:
      - back-worker-database
      - back-eurekaserver
      - back-apigateway
    networks:
      - eureka_network
      - database_network

networks:
  database_network:
  eureka_network:
