# docker swarm init
# docker stack deploy -c docker-swarm.yml cloudb

version: '3.8'

services:
  # 프론트 컨테이너
  front:
    image: devtae/front
    ports:
      - "80:80"
    networks:
      - eureka_network
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s


  # 데이터베이스 컨테이너
  back-worker-database:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BACK_WORKER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - ./back-worker-data:/var/lib/postgresql/data
      - ./back-worker-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s

  back-work-database:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BACK_WORK}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - ./back-work-data:/var/lib/postgresql/data
      - ./back-work-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s


  # 백엔드 컨테이너
  back-eurekaserver:
    image: devtae/back-eurekaserver
    ports:
      - "8761:8761"
    networks:
      - eureka_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s

  back-apigateway:
    image: devtae/back-apigateway
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
    depends_on:
      - back-eurekaserver
    networks:
      - eureka_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s

  back-worker:
    image: devtae/back-worker
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://back-worker-database:5432/back_worker
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_ZIPKIN_BASE_URL: http://back-zipkin:9411
      API_GATEWAY_URL: http://back-apigateway:9000
    volumes:
      - ./logs:/logs
    networks:
      - eureka_network
      - database_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s

  back-work:
    image: devtae/back-work
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://back-work-database:5432/back_work
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_ZIPKIN_BASE_URL: http://back-zipkin:9411
      API_GATEWAY_URL: http://back-apigateway:9000
    volumes:
      - ./logs:/logs
    networks:
      - eureka_network
      - database_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/actuator/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s

  back-dashboard:
    image: devtae/back-dashboard
    ports:
      - "9003:9003"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_ZIPKIN_BASE_URL: http://back-zipkin:9411
      API_GATEWAY_URL: http://back-apigateway:9000
    volumes:
      - ./logs:/logs
    networks:
      - eureka_network
      - database_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/actuator/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s


  # 백엔드 로그 트레이싱
  back-zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - eureka_network
    deploy: # t3-medium (2 cpus, ram 4gb 기준) 
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s


networks:
  database_network:
  eureka_network: