version: '3'

services:
  back-eurekaserver:
    container_name: back-eurekaserver
    image: devtae/back-eurekaserver
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - eureka_network

  back-apigateway:
    container_name: back-apigateway
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_CLOUD_INETUTILS_IGNORED_INTERFACES: eureka_network
    depends_on:
      - back-eurekaserver
    networks:
      - eureka_network


  database:
    container_name: postgres_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: back_worker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: 'Asia/Seoul'
    networks:
      - database_network

  back-worker:
    container_name: back-worker
    restart: on-failure
    build:
      context: ./back-worker
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/back_worker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://back-eurekaserver:8761/eureka
      SPRING_CLOUD_INETUTILS_IGNORED_INTERFACES: eureka_network
    depends_on:
      - database
      - back-eurekaserver
      - back-apigateway
    networks:
      - eureka_network
      - database_network

networks:
  database_network:
  eureka_network:
